### ISSUE TITLE
group.sh generate excel file failed

### ISSUE THREAD

**Issue by arm7star** [will-mei/cfiojobs#2]
fio json report file miss deviation key and the cfiojobs.log2.py failed to generate excel file.
what is the fio version used by cfiojobs and the fio's parameters?
thanks!

**Comment by will-mei** [comment]
to get the right output you should use fio 3.1+, and i'll put this info into the readme file later. 

sorry for replying you so late, really thank you for your feedback, well, the truth is I've been busy with other things (not related with the disk testing work any more), so I don't have a clear plan on fixing the bug or refactoring the code of this script in the forthcoming months , and there will be no update till the end of this year.
